name: Lint and Test

on:
  push:
    branches:
      - beta
      - main
  pull_request:
    branches:
      - beta
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install PNPM
      - name: Install PNPM
        uses: pnpm/action-setup@v4

      # Set up Node.js for PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'

      # Install PNPM dependencies
      - name: Install PNPM dependencies
        run: pnpm install --frozen-lockfile

      # Install Playwright
      - name: Install Playwright
        run: pnpm exec playwright install

      # Lint TS and SCSS files
      - name: Run lint (TS and SCSS)
        run: pnpm lint

      # Test TS files
      - name: Run tests (TS)
        run: pnpm test
